"""Add post_reactions, post_comments and saved_recommendations

Revision ID: 2e8572292d48
Revises: fff75ee30e9a
Create Date: 2026-04-21 20:12:36.006905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8572292d48'
down_revision: Union[str, None] = 'fff75ee30e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['catch_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['catch_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('waterbody_id', sa.Integer(), nullable=True),
    sa.Column('rod_id', sa.Integer(), nullable=True),
    sa.Column('jacket_id', sa.Integer(), nullable=True),
    sa.Column('pants_id', sa.Integer(), nullable=True),
    sa.Column('shoes_id', sa.Integer(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('lure_id', sa.Integer(), nullable=True),
    sa.Column('groundbait_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['groundbait_id'], ['groundbaits.id'], ),
    sa.ForeignKeyConstraint(['head_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['jacket_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['lure_id'], ['lures.id'], ),
    sa.ForeignKeyConstraint(['pants_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['rod_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['shoes_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_recommendations')
    op.drop_table('post_reactions')
    op.drop_table('post_comments')
    # ### end Alembic commands ###
