"""Add waterbody_id to ForumTopic

Revision ID: b4408dde9edb
Revises: 076bdfe46d3e
Create Date: 2026-04-10 15:03:34.052332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4408dde9edb'
down_revision: Union[str, None] = '076bdfe46d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_topics', sa.Column('waterbody_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forum_topics', 'waterbodies', ['waterbody_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_topics', type_='foreignkey')
    op.drop_column('forum_topics', 'waterbody_id')
    # ### end Alembic commands ###
