"""add new tables

Revision ID: cfc1b8884350
Revises: 
Create Date: 2026-03-29 15:54:07.645315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc1b8884350'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fishing_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('ROD', 'JACKET', 'HEAD', 'PANTS', 'SHOES', name='inventorycategory'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('preview_image_url', sa.String(length=255), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('season_use', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_of_year', sa.String(length=50), nullable=False),
    sa.Column('avg_temperature', sa.Float(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waterbodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('avg_depth', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('accessibility', sa.Text(), nullable=True),
    sa.Column('boats_allowed', sa.Boolean(), nullable=False),
    sa.Column('clarity', sa.String(length=50), nullable=True),
    sa.Column('vegetation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_type', sa.String(length=50), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avg_size', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('is_rare', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['fish_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('equipped_rod_id', sa.Integer(), nullable=True),
    sa.Column('equipped_jacket_id', sa.Integer(), nullable=True),
    sa.Column('equipped_head_id', sa.Integer(), nullable=True),
    sa.Column('equipped_pants_id', sa.Integer(), nullable=True),
    sa.Column('equipped_shoes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipped_head_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['equipped_jacket_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['equipped_pants_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['equipped_rod_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['equipped_shoes_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('waterbody_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waterbody_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=100), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('bottom_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catch_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('waterbody_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_waterbodies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('waterbody_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'waterbody_id')
    )
    op.create_table('fish_inventory_link',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('rigging_advice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('fish_id', 'inventory_id')
    )
    op.create_table('fish_lure_link',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('lure_id', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.String(length=50), nullable=True),
    sa.Column('used_color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['lure_id'], ['lures.id'], ),
    sa.PrimaryKeyConstraint('fish_id', 'lure_id')
    )
    op.create_table('fish_season_link',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('habitat_depth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('fish_id', 'season_id')
    )
    op.create_table('fish_time_link',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['fishing_times.id'], ),
    sa.PrimaryKeyConstraint('fish_id', 'time_id')
    )
    op.create_table('fish_waterbody_link',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('waterbody_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('fish_id', 'waterbody_id')
    )
    op.create_table('fish_weather_link',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('influence_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['weather_conditions.id'], ),
    sa.PrimaryKeyConstraint('fish_id', 'weather_id')
    )
    op.create_table('forum_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groundbaits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('season_use', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_inventory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'inventory_id')
    )
    op.create_table('waterbody_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('waterbody_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waterbody_id'], ['waterbodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_messages')
    op.drop_table('waterbody_reviews')
    op.drop_table('user_inventory')
    op.drop_table('groundbaits')
    op.drop_table('forum_topics')
    op.drop_table('fish_weather_link')
    op.drop_table('fish_waterbody_link')
    op.drop_table('fish_time_link')
    op.drop_table('fish_season_link')
    op.drop_table('fish_lure_link')
    op.drop_table('fish_inventory_link')
    op.drop_table('favorite_waterbodies')
    op.drop_table('catch_posts')
    op.drop_table('waterbody_spots')
    op.drop_table('users')
    op.drop_table('fishes')
    op.drop_table('weather_conditions')
    op.drop_table('waterbodies')
    op.drop_table('seasons')
    op.drop_table('lures')
    op.drop_table('inventory')
    op.drop_table('fishing_times')
    op.drop_table('fish_categories')
    # ### end Alembic commands ###
