"""Add advice field to SavedRecommendation

Revision ID: f708fe4332d0
Revises: 2e8572292d48
Create Date: 2026-04-21 20:36:22.496725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f708fe4332d0'
down_revision: Union[str, None] = '2e8572292d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_recommendations', sa.Column('advice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_recommendations', 'advice')
    # ### end Alembic commands ###
