"""add_region_to_waterbody

Revision ID: fb0c2651ebf7
Revises: b4408dde9edb
Create Date: 2026-04-13 14:14:57.064846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0c2651ebf7'
down_revision: Union[str, None] = 'b4408dde9edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waterbodies', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waterbodies', 'region')
    # ### end Alembic commands ###
