"""Add filter_type to Inventory

Revision ID: fff75ee30e9a
Revises: fb0c2651ebf7
Create Date: 2026-04-19 16:50:04.817875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff75ee30e9a'
down_revision: Union[str, None] = 'fb0c2651ebf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('filter_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'filter_type')
    # ### end Alembic commands ###
